default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: Pinly_development

test:
  <<: *default
  database: Pinly_test

production:
  <<: *default
  database: Pinly_production
  username: Pinly
  password: <%= ENV['PINLY_DATABASE_PASSWORD'] %>
